version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ls
    volumes:
      - app-volume:/usr/src/build
  backend:
    build: .
    command: bundle exec rails s -p 3000
    volumes:
      - app-volume:/usr/src/public
    ports:
      - "3000:3000"
    environment:
      PSQL_HOST: "db"
    depends_on:
      - db

volumes:
  app-volume:
